gestionFestival/Controllers/ResponsableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI.WebControls;
using System.Web.Mvc;
using gestionFestival.Models;
using gestionFestival.ViewModel;


namespace gestionFestival.Controllers
{
    public class ResponsableController : Controller
    {
        //Cette méthode calculera les dépenses et recettes du poste 
        public CPoste CalculBudgetPoste()
        {
            CPoste poste = new CPoste(((CResponsable)Session["user"]).Id);
            double totalDepense= poste.Depense.Total-poste.Recette.Total ;
            poste.BudgetActuel = poste.BudgetDepart - totalDepense;
            poste.ModifierBudget(poste.BudgetActuel);
            return poste;
        }

        //Testera si une session existe , si aucune session n est trouvée
        //Vous etes redirigé vers le login screen
        public bool TestSession()
        {
            if (Session["user"] == null)
                return false;
            else
                return true;
        }

        //Retourne vers l' index
        //Et met le poste dans la session
        public ActionResult Index()
        {
            if (!TestSession())
                return Redirect("Login?error=Vous devez être connecté avant d acceder aux ressources");
            
           CPoste poste = CalculBudgetPoste();
            Session["poste"] = poste;
           
            return View(poste);
        }

        
        /************************/
        /*  Gestion matériel    */
        /************************/

        //Page principale de la gestion de matériel
        public ActionResult GestionMateriel()
        {
            if (!TestSession())
                return Redirect("../Login?error=Vous devez être connecté avant d acceder aux ressources");

            CResponsable resp = (CResponsable)Session["user"];
            CPoste post = (CPoste)Session["poste"];   
            if (Session["listMateriel"]==null) {
                List<CMateriel> list = resp.ConsultListMateriel(post.Id);
                Session["listMateriel"] = list;
                return View("GestionMateriel");
            }
            else
            {
                return View("GestionMateriel");
            }

        }

        //Methode de suppresion de matériel
        public ActionResult SuppressionMateriel(int id)
        {
            CResponsable resp=(CResponsable)Session["user"];
            CMateriel mat = ((List<CMateriel>)Session["listMateriel"]).ElementAt(id);         
            resp.DemandeSuppressionMateriel(mat);
            ((List<CMateriel>)Session["listMateriel"]).RemoveAt(id); 
            return View("GestionMateriel");
        }

        
        //Méthode pour l' ajout du matériel
        public ActionResult AjouterMateriel(string nom, double prix, int qtt)
        {
            CResponsable resp = (CResponsable)Session["user"];
            CMateriel mat = new CMateriel(nom,prix,qtt);
            //Test si la demande peut être acceptée en fonction du budget
            if (resp.DemandeAjoutMateriel(mat, ((CPoste)Session["poste"]).Id))
            {
                Session["listMateriel"] = null;
                return Redirect("GestionMateriel");
            }
            else
            {   
                return Redirect("GestionMateriel?error=Erreur: pas assez de fond");
            }
        }

        //Renvoi au formulaire de modification
        public ActionResult ModifMaterialForm(int id)
        {
            List<CMateriel> list = (List<CMateriel>)Session["listMateriel"];
            CMateriel mat = list.ElementAt(id);
            ViewBag.index = id;

            return View("ModifMatForm",mat);
        }

        //Méthode qui modifiera le matériel
        public ActionResult ModifMat(string nom, double prix , int qtt,int index)
        {
            CResponsable resp = (CResponsable)Session["user"];
            List<CMateriel> list = (List<CMateriel>)Session["listMateriel"];
            CPoste poste = CalculBudgetPoste(); 
            CMateriel mat = list.ElementAt(index);
            //Test si la demande peut être acceptée en fonction du budget
            if (resp.DemandeModificationMateriel(mat, nom, prix, qtt, poste.Id))
            {
                return Redirect("GestionMateriel");
            }
            else
            {
                Session["listMateriel"] = null;
                return Redirect("GestionMateriel?error=Erreur: pas assez de fond");
            }
        }




        /************************/
        /*  Gestion participant */
        /************************/

        //Vue principale de la gestion des participant
        public ActionResult GestionParticipant()
        {
            if (!TestSession())
                return Redirect("../Login?error=Vous devez être connecté avant d acceder aux ressources");

            CResponsable resp = (CResponsable)Session["user"];
            CPoste post = (CPoste)Session["poste"];

            Session["listPersonnel"] = resp.ConsultListPersonnel();
            
            //Test, si la session de la liste est nulle , rappelle la méthode pour la consultation
            if (Session["listParticipant"] == null)
            {           
                Session["listParticipant"] = resp.ConsultListParticipant(post.Id) ;  
                return View("GestionParticipant");
            }
            else
            {
                return View("GestionParticipant");

            }
        }

        //Méthode de supression des participant
        public ActionResult SuppressionParticipant(int id)
        {
            CResponsable resp = (CResponsable)Session["user"];
            CParticipant part = ((List<CParticipant>)Session["listParticipant"]).ElementAt(id);
            resp.DemandeSuppressionParticipant(part);
            ((List<CParticipant>)Session["listParticipant"]).RemoveAt(id);
            return Redirect("../GestionParticipant");
        }

        //Méthode d' ajout des participants
        public ActionResult AjouterParticipant(double salaire, int heureTravail)
        {    
            int id =Convert.ToInt32(Request.Form["personnel"]);
            CResponsable resp = (CResponsable)Session["user"];
            CPersonnel persToAdd = ((List<CPersonnel>)Session["listPersonnel"]).ElementAt(id);
            CParticipant part = (CParticipant)persToAdd;
            part.Salaire = salaire;
            part.HeureTravail = heureTravail;
            //Test si le budget est suffisant
            if (resp.DemandeAjoutParticipant(part, ((CPoste)Session["poste"]).Id))
            {
                Session["listParticipant"] = null;
                return Redirect("GestionParticipant");
            }
            else
            {

                return Redirect("GestionParticipant?error=Erreur: pas assez de fond");
            }

        }

        //Renvoi au formulaire de modification
        public ActionResult ModifParticipantForm(int id)
        {
            List<CParticipant> list = (List<CParticipant>)Session["listParticipant"];
            CParticipant part = list.ElementAt(id);
            ViewBag.index = id;

            return View("ModifParticipantForm", part);
        }

        //Methode de modification du personnel
        public ActionResult ModifParticipant(double salaire, int heureTravail, int index)
        {
          
            List<CParticipant> list = (List<CParticipant>)Session["listParticipant"];
            CResponsable resp = (CResponsable)Session["user"];
            list.ElementAt(index).Salaire = salaire;
            list.ElementAt(index).HeureTravail = heureTravail;          
            CParticipant part = list.ElementAt(index);
            //Test si la modification ne dépasse pas le budget
            if (resp.DemandeModificationParticipant(part, salaire, heureTravail, ((CPoste)Session["poste"]).Id))
            {
                return Redirect("GestionParticipant");
            }
            else
            {
                Session["listParticipant"] = null;
                return Redirect("GestionParticipant?error=Erreur: pas assez de fond");
            }
        }



        /************************/
        /*    Gestion Revenu    */
        /************************/

         //Vue principale de la gestio des revenus
        public ActionResult GestionRevenu()
        {
            if (!TestSession())
                return Redirect("../Login?error=Vous devez être connecté avant d acceder aux ressources");
            CResponsable resp = (CResponsable)Session["user"];
            CPoste post = (CPoste)Session["poste"];
            if (Session["listRevenu"] == null)
            { 
                Session["listRevenu"] = resp.ConsultListRevenu(post.Id);
                return View("GestionRevenu");
            }
            else
            {
                return View("GestionRevenu");
            }

        }

        //Méthode de suppression du revenu
        public ActionResult SuppressionRevenu(int id)
        {
            CResponsable resp = (CResponsable)Session["user"];
            CRevenu rev = ((List<CRevenu>)Session["listRevenu"]).ElementAt(id);
            resp.DemandeSuppressionRevenu(rev);
            ((List<CRevenu>)Session["listRevenu"]).RemoveAt(id);
            return View("GestionRevenu");
        }

        //Méthode d' ajout de revenu
        public ActionResult AjouterRevenu(string description, double montant)
        {
            CResponsable resp = (CResponsable)Session["user"];
            CRevenu rev = new CRevenu(description, montant);
            resp.DemandeAjoutRevenu(rev, ((CPoste)Session["poste"]).Id);
            Session["listRevenu"] = null;
            return Redirect("GestionRevenu");
        }

        //Renvoi au formulaire de modification
        public ActionResult ModifRevenuForm(int id)
        {
            List<CRevenu> list = (List<CRevenu>)Session["listRevenu"];

gestionFestival/Views/Responsable/DemandeForm.cshtml
@using gestionFestival.Models

@using (Html.BeginForm("AddDemande", "Responsable"))
{

   
    <label>Motif de la demande</label>
    <input type="text"  name="motif" required="required" />
    <label>Prix</label>
    <input type="number"  name="montant" min="0" required="required"/>
    
    
    <input type="submit" value="Confirmer la modification" />

}

gestionFestival/Views/Responsable/Index.cshtml
@using gestionFestival.ViewModel;
@using gestionFestival.Models;

@{
    Layout = "~/Views/Shared/headerResponsable.cshtml";
    CPoste Poste = Model;

}
<h1>Poste: @Poste.NomPoste</h1>

@{ 

    
    <div id="listMat">
        <label>Liste du matériel</label>
        <table border="1">
            <tr><th>Nom</th><th>prix par unité</th><th>quantité</th><th>Total</th>
            @{double somme = 0; }
            @foreach (CMateriel mat in Poste.Depense.ListMat.ListeMat)
            {
                <tr>
                    <td>@mat.Nom</td>
                    <td>@mat.Prix €</td>
                    <td>@mat.Quantite</td>
                    <td>@(mat.Prix * mat.Quantite) €</td>
                </tr>
                somme += mat.Prix * mat.Quantite;
            }
        </table>

    </div>

    <label>Liste des participants</label>
    <div id="listPart">

         <br/>

        <table border="1">
            <tr>
                <th>Nom</th>
                <th>email</th>
                <th>Téléphone</th>
                <th>Salaire</th>
            
                @foreach (CParticipant part in Poste.Depense.ListPart.ListePart)
                {
                <tr>
                    <td>@part.Nom  @part.Prenom</td>
                    <td>@part.Mail</td>
                    <td>@part.Telephone</td>
                    <td>@part.Salaire €</td>
                </tr>
                    somme +=part.Salaire;
                }
            </table>

    </div>



    <label>Liste des revenus</label>
    <div id="listRev" >

        <table  border="1">
            <tr>
                <th>Description</th>
                <th>Montant</th>
               

                @foreach (CRevenu rev in Poste.Recette.ListRev.ListeRev)
                {
                <tr>
                    <td>@rev.Description</td>
                    <td>@rev.Montant €</td>
                    
                </tr>
                    somme -= rev.Montant;
                }
            </table>

        </div>


    <label>Budget</label>
    <div id="budget">@somme/@Poste.BudgetDepart</div>
}

gestionFestival/Views/Responsable/ModifMatForm.cshtml
@using gestionFestival.Models

@using (Html.BeginForm("ModifMat", "Responsable"))
{

    CMateriel mat = Model;
    <label>Nom</label>
    <input type="text" value="@mat.Nom" name="nom"/>
    <label>Prix</label>
    <input type="number" value="@mat.Prix" name="prix" />
    <label>Quantité</label>
    <input type="number" value="@mat.Quantite" name="qtt" />
    <input type="hidden" value="@ViewBag.index" name="index"/>
    <input type="submit" value="Confirmer la modification"/>

}

gestionFestival/Views/Responsable/ModifParticipantForm.cshtml
@using gestionFestival.Models

@using (Html.BeginForm("ModifParticipant", "Responsable"))
{

    CParticipant part = Model;
    <h1>Fiche du participant @part.Prenom  @part.Nom</h1>
    <label>Salaire</label>
    <input type="number" value="@part.Salaire" name="salaire" />
    <label>Heure travail</label>
    <input type="number" value="@part.HeureTravail" name="heureTravail" />
    <input type="hidden" value="@ViewBag.index" name="index" />


    <input type="submit" value="Confirmer la modification" />

}

gestionFestival/Views/Responsable/ModifRevenuForm.cshtml
@using gestionFestival.Models

@using (Html.BeginForm("ModifRevenu", "Responsable"))
{

    CRevenu rev = Model;
    <label>Nom</label>
    <input type="text" value="@rev.Description" name="description" />
    <label>Prix</label>
    <input type="number" value="@rev.Montant" name="montant" />
    <label>Quantité</label>
   
    <input type="hidden" value="@ViewBag.index" name="index" />
    <input type="submit" value="Confirmer la modification" />

}

gestionFestival/Views/Responsable/gestionBudget.cshtml
@using gestionFestival.Models;

@{
    Layout = "~/Views/Shared/headerResponsable.cshtml";

    CPoste poste = Model;

    <h1>Budget restant au poste @poste.NomPoste =@poste.BudgetActuel/@poste.BudgetDepart</h1>

    <h1>Dépensé : @poste.Depense.Total</h1>
    <h1>Recette : @poste.Recette.Total</h1>

    <br />

    @Html.ActionLink("Introduire une demande", "DemandeForm", "Responsable", null, null)
    <br/>
    foreach (CDemande dem in ViewBag.listDem)
    {
        <label>Demande du : @dem.Date.ToString()</label>
        <label>Motif</label>
        <p>@dem.Motif</p>
        <label>Montant : @dem.Montant</label>

    }

}

gestionFestival/Views/Responsable/gestionMateriel.cshtml
@using gestionFestival.Models;

<table border="1">
    <tr><th>Nom</th><th>prix par unité</th><th>quantité</th><th>Total</th><th></th><th></th></tr>
    @{

        CResponsable r = (CResponsable)Session["user"];
        Layout = "~/Views/Shared/headerResponsable.cshtml";
        int i = 0;
        foreach (CMateriel mat in (List<CMateriel>)Session["listMateriel"])
        {
            <tr>
                <td>@mat.Nom</td>
                <td>@mat.Prix €</td>
                <td>@mat.Quantite</td>
                <td>@(mat.Prix * mat.Quantite) €</td>
                <td><button onclick="">@Html.ActionLink("Suppression Matériel", "SuppressionMateriel", "Responsable", new { id = i }, null)</button></td>
                <td><button onclick="">@Html.ActionLink("Modification", "ModifMaterialForm", "Responsable", new { id = i++ }, null)</button></td>
                
            </tr>

        }


    }
            <tr><th>Nom</th> <th>Prix</th> <th>Quantité</th></tr>
            @using (Html.BeginForm("AjouterMateriel", "Responsable"))
            {
                <tr>
                    <td><input type="text" name="nom" required="required" /></td>
                    <td><input type="number" name="prix" required="required" /></td>
                    <td><input type="number" name="qtt" required="required" /></td>

                    <td><input type="submit" value="Ajouter" required="required" /></td>
                </tr>

            }
                
</table>

<h1>@Request.QueryString["error"]</h1>

gestionFestival/Views/Responsable/gestionParticipant.cshtml
@using gestionFestival.Models;
@using System.Web.UI.WebControls;


<table border="1">
    <tr><th>Identité</th><th>email</th><th>tel</th><th>Salaire</th><th></th><th></th></tr>
    @{

        CResponsable r = (CResponsable)Session["user"];
        Layout = "~/Views/Shared/headerResponsable.cshtml";
        int i = 0;
        foreach (CParticipant part in (List<CParticipant>)Session["listParticipant"])
        {
            <tr>
                <td>@part.Nom</td>
                <td>@part.Mail €</td>
                <td>@part.Telephone</td>
                <td>@part.Salaire €</td>
                <td><button onclick="">@Html.ActionLink("Renvoi", "SuppressionParticipant", "Responsable", new { id = i }, null)</button></td>
                <td><button onclick="">@Html.ActionLink("Modifier Info", "ModifParticipantForm", "Responsable", new { id = i++ }, null)</button></td>

            </tr>
        }
    }
</table>

    

@using (Html.BeginForm("AjouterParticipant", "Responsable"))
{
      <select name="personnel">
        @{int j = 0;}
            @foreach(CPersonnel p in (List<CPersonnel>)Session["listPersonnel"]) {
         <option value="@(j++)">@p.Nom  @p.Prenom   Spécialisation: @p.Specialisation </option>
        }
    </select>
    <label>Salaire</label>
    <input type="number" min="0" name="salaire"/>
    <label>Heure de travail</label>
    <input type="number" min="0" name="heureTravail"/>
     <input type="submit" value="Ajouter" required="required" />


}

<h1>@Request.QueryString["error"]</h1>

gestionFestival/Views/Responsable/gestionRevenu.cshtml
@using gestionFestival.Models;

<table border="1">
    <tr><th>Description du revenu</th><th>Montanbt</th><th></th><th></th></tr>
    @{

        CResponsable r = (CResponsable)Session["user"];
        Layout = "~/Views/Shared/headerResponsable.cshtml";
        int i = 0;
        foreach (CRevenu rev in (List<CRevenu>)Session["listRevenu"])
        {
            <tr>
                <td>@rev.Description</td>
                <td>@rev.Montant €</td>
                
                <td><button onclick="">@Html.ActionLink("Suppression Revenu", "SuppressionRevenu", "Responsable", new { id = i }, null)</button></td>
                <td><button onclick="">@Html.ActionLink("Modification", "ModifRevenuForm", "Responsable", new { id = i++ }, null)</button></td>

            </tr>

        }


    }
    <tr><th>Description</th> <th>Montant</th> </tr>
    @using (Html.BeginForm("AjouterRevenu", "Responsable"))
            {
        <tr>
            <td><input type="text" name="description" required="required" /></td>
            <td><input type="number" name="montant" required="required" /></td>
           

            <td><input type="submit" value="Ajouter" required="required" /></td>
        </tr>

    }

</table>