gestionFestival/Controllers/ComptableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using gestionFestival.Models;
using gestionFestival.ViewModel;

namespace gestionFestival.Controllers
{
    public class ComptableController : Controller
    {
        // GET: Comptable
        public ActionResult Index()
        {
            CFestival festival = new CFestival();
            festival.InfoFestival();
            CComptable comptable = new CComptable();
            ViewBag.budgetTotalDisponible= comptable.ConsultertotalDisponible();

            return View(festival);
        }

        // Gestion des recettes
        public ActionResult GestionRecette()
        {
            CComptable comptable = new CComptable();
            ViewBag.listeDesPostes = comptable.ConsulterListePoste();

            return View();
        }

        // Gestion des dépenses
        public ActionResult GestionDepense()
        {
            CComptable comptable = new CComptable();
            ViewBag.listeDesPostes = comptable.ConsulterListePoste();
            return View();
        }
        
        // Gestion des demandes
        public ActionResult GestionDemande()
        {
            listDemande listDemande = new listDemande();
            ViewBag.listeDemande=listDemande.GetList();
            return View();
        }
        public ActionResult DemandeDeBudget(int idDemande, double budget, int idPers)
        {
            CComptable comptable = new CComptable();
            if(idPers != 0)
            {
                comptable.AccepterDemandeBudget(idPers, budget, idDemande);
                ViewBag.message = "La demande a été acceptée";
            }
            else
            {
                comptable.RefuserDemandeBudget(idDemande);
                ViewBag.message = "La demande a été refusée";
            }
            listDemande listDemande = new listDemande();
            ViewBag.listeDemande = listDemande.GetList();
            return View("GestionDemande");
        }

        // Assignation des budget
        public ActionResult GestionBudget()
        {
            CComptable comptable = new CComptable();
            ViewBag.listeDesPostes = comptable.ConsulterListePoste();
            return View();
        }
        public ActionResult GestionCompte(int id, string nom, double budgetActuel, double budgetDepart, string description, CDepense dep, CRecette rec)
        {
            CPoste poste = new CPoste(id,nom,budgetActuel,budgetDepart,description,dep,rec);
            ViewBag.id = poste.Id;
            return View(poste);
        }
        [HttpPost]
        public ActionResult UpdateBudget(int id,string budget)
        {
            double montant;
            CComptable comptable = new CComptable();
            bool result = double.TryParse(budget, out montant);
            if (result && montant > 0)
            {
                ViewBag.message = "Budget confirmé";
                comptable.AllouerBudget(id, montant);
            }
            else
            {
                ViewBag.message = "Veuillez entrer une valeur correcte";
            }
            ViewBag.listeDesPostes = comptable.ConsulterListePoste();
            return View("GestionBudget");
        }
    }
}

gestionFestival/Views/Comptable/GestionBudget.cshtml
@using gestionFestival.Models
@{
    Layout = "~/Views/Shared/headerComptable.cshtml";
    ViewBag.Title = "GestionDemande";
}
<br />
<div>
    <br />
    <table>
        <tr><td colspan="2"><h2>Poste sans budget</h2></td></tr>
        @foreach (CPoste liste in ViewBag.listeDesPostes)
        {
            if (liste.BudgetDepart == 0)
            {
                <tr>
                    <td>@liste.NomPoste</td>
                    <td><button onclick="">@Html.ActionLink("Gérer le compte", "GestionCompte", "Comptable", new { id = liste.Id, nom = liste.NomPoste, budgetActuel = liste.BudgetActuel, budgetDepart = liste.BudgetDepart, description = liste.Description, dep = liste.Depense, rec = liste.Recette }, null)</button></td>
                </tr>
            }
        }
    </table>
    <br />
    <h3>@ViewBag.message</h3>
</div>

gestionFestival/Views/Comptable/GestionCompte.cshtml
@model gestionFestival.Models.CPoste
@using gestionFestival.Models

@{
    Layout = "~/Views/Shared/headerAdmin.cshtml";
    ViewBag.Title = "ModiferPoste";
}
<br />
@using (Html.BeginForm("UpdateBudget", "Comptable"))
{
    <fieldset>
        <legend>Gérer le budget du poste @Html.TextBoxFor(model => model.NomPoste, new { @readonly = "readonly" }) </legend>
        
        <input type="hidden" value="@ViewBag.id" name="id" />

        <div>
            @Html.Label("Quel budget voulez-vous alloué au poste ?")
            @Html.TextBox("budget")
        </div>
        <div>
            @ViewBag.message
        </div>
        <br />
        <input type="submit" value="Confirmer la demande" />
        <button onclick="">@Html.ActionLink("Annuler", "GestionBudget", "Comptable")</button>
    </fieldset>
}

gestionFestival/Views/Comptable/GestionDemande.cshtml
@using gestionFestival.Models
@{ 
    Layout = "~/Views/Shared/headerComptable.cshtml";
    ViewBag.Title = "GestionDemande";

}
    


<h2>@ViewBag.message</h2>
<div>
    <table>
        <tr><td colspan="5"><h2>Gestion des demandes de budgets</h2></td></tr>
        @foreach (CDemande demande in ViewBag.listeDemande)
        {
            <tr>
                <td>@demande.Date.ToString("dd/MM/yyyy")</td>
                <td>@demande.Motif </td>
                <td>(@demande.Montant) €  </td>
                <td><button onclick="">@Html.ActionLink("Accepter", "DemandeDeBudget", "Comptable", new { idDemande = demande.Id, budget = demande.Montant, idPers = demande.IdPersonne  }, null)</button></td>
                <td><button onclick="">@Html.ActionLink("Refuser", "DemandeDeBudget", "Comptable", new { idDemande = demande.Id, budget = demande.Montant, idPers = demande.IdPersonne }, null)</button></td>
            </tr>
        }
    </table>
    
</div>

gestionFestival/Views/Comptable/GestionDepense.cshtml
@model gestionFestival.Models.CPoste
@using gestionFestival.Models
@{
    Layout = "~/Views/Shared/headerComptable.cshtml";
    ViewBag.Title = "GestionDepense";
}
<br />
<div>
    <table>
        <tr><td colspan="4"><h2>Gestion des dépenses</h2></td></tr>
        @foreach (CPoste poste in ViewBag.listeDesPostes)
        {
            <tr>
                <td>@poste.NomPoste</td>
                <td>@poste.Depense.Total</td>
            </tr>
        }
    </table>

</div>

gestionFestival/Views/Comptable/GestionRecette.cshtml
@model gestionFestival.Models.CPoste
@using gestionFestival.Models
@{
    Layout = "~/Views/Shared/headerComptable.cshtml";
    ViewBag.Title = "GestionDepense";
}
<br />
<div>
    <table>
        <tr><td colspan="4"><h2>Gestion des recettes</h2></td></tr>
        @foreach (CPoste poste in ViewBag.listeDesPostes)
        {
            <tr>
                <td>@poste.NomPoste</td>
                <td>@poste.Recette.Total</td>
            </tr>
        }
    </table>

</div>

gestionFestival/Views/Comptable/Index.cshtml
@model gestionFestival.Models.CFestival
@{
    Layout = "~/Views/Shared/headerComptable.cshtml";
}
@{
    ViewBag.Title = "Accueil";
}

<h1>@Model.NomFestival</h1>
<h2>du @Model.DateDebutFestival.ToString("dd/MM/yyyy") au @Model.DateFinFestival.ToString("dd/MM/yyyy")</h2>
<p>Budget total du festival : @Model.BudgetFestival</p>
<p>Budget encore disponible : @(Model.BudgetFestival-ViewBag.budgetTotalDisponible)</p>